### ISSUE TITLE
Incorrect pixel card width

### ISSUE THREAD

**Issue by Martin2Constant** [QishengLi/virtual_chinrest#1]
Hello, 

I have encountered a bug using your script. The size in pixels of the credit card is inexact on all my monitors. 

On my 24" Samsung CFG73 (520mm width, 1920x1080 resolution), the returned cardWidthPx value is 351px. However, the actual width is closer to 318px (Obtained via capturing the screen area of the virtual card, that was the easiest method I found, although it is a bit imprecise). 
Calculating screen width from cardWidthPx gives a width of 1920/(351/85.6) = 468mm whereas using the screenshot width outputs 517mm (much closer to real size).

On my 22" LG L226-WA (475mm width, 1680x1050), cardWidthPx = 342px and screenshot width = 298px. 
Screen width with cardWidthPx = 421mm, with screenshot width = 482mm.

Finally, on my 55" LG C8 (1225mm width, 3840x2160), cardWidthPx = 297px and screenshot width = 269px.
Screen width with cardWidthPx = 1107mm, with screenshot width = 1222mm.

Sadly, I have no idea how to fix this.

Best regards,
Martin Constant.

**Comment by QishengLi** [comment]
Thanks for your interest in our work!

The inaccuracy might be due to the difference between the hardware pixel vs. the software pixel (also called CSS pixel, or what we really see through web browsers). Different devices also have different DPI. So we think it's possible that our method is not returning the exact screen resolution and/or viewing distances.
Is there another way that you could verify whether the method could be useful to replicate in-lab studies?

I will keep looking into this and see what I can do.

**Comment by Martin2Constant** [comment]
The problem came from the fact that card.png has transparent "borders". When setting the slider to the maximum, the reported card width is 900px but the visible card doesn't fill the whole div (which is 900px wide). Luckily, the fix is as easy as removing the transparent borders, and cardWidthPx is now accurate. I'm attaching the png file of the fixed card.
![card_fixed](https://user-images.githubusercontent.com/25343725/81417719-e2b04900-914b-11ea-8b53-b1bdd5d8abc0.png)

**Comment by QishengLi** [comment]
Thank you so much!

I just updated the card image in the repo. Sorry about the confusion -- we used a different card image for our experiments and then created this new one but missed the borders.
